export const GameState = {
  INIT_GAME: 'INIT_GAME',
  START_GAME: 'START_GAME',
  CONTINUE_GAME: 'CONTINUE_GAME',
  END_GAME: 'END_GAME'
}

export const Actions = {
  CLEAR_STATE: 'CLEAR_STATE',
  INC_BET_CREDITS: 'INC_BET_CREDITS',
  UPDATE_TOTAL_CREDITS: 'UPDATE_TOTAL_CREDITS',
  UPDATE_GAME_STATE: 'UPDATE_GAME_STATE'
}
