export const OPEN_ADMIN_DIALOG = 'OPEN_ADMIN_DIALOG'
export const CLOSE_ADMIN_DIALOG = 'CLOSE_ADMIN_DIALOG'
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const RESET_SETTINGS = 'RESET_SETTINGS'
